spring:
  application:
    name: journal App
  data:
    mongodb:
          uri: <Connection URI>
          database: journaldb
          auto-indexed-creation: true

server:
  port: 8080
  error:
    include-message=always: always
